### ISSUE TITLE
.scdignore

### ISSUE THREAD

**Issue by xenoterracide** [pavoljuhas/smart-change-directory#6]
just tried this out with recursive, and man, does this thing need an ignore file... I didn't want to index all `.git` and all `node_modules`

suggesting an ignore file similar to `.gitignore`

**Comment by pavoljuhas** [comment]
That is already in. :-)  Please see the FILES section in the [README](../#files).
You can add the following line to `~/.scdignore`
```
*/node_modules/*
```
I am a bit surprised you got `.git` paths in the index.  `scd -a -r` should skip dotted directories unless they are explicitly passed as arguments.
Can you provide more detail how did you do recursive index?
Note that unvisited paths fade away in few days and are then excluded from scd selection menu (unless they are the only matches).

**Comment by xenoterracide** [comment]
yeah, git files weren't being included, that was just an assumption... a bad one, but uh, this `.scdignore` doesn't appear to be taking effect. I keep expecting to get `IdeaProjects/aurelia` but it's not showing up and stuff in node_modules is

```
> scd -a -r IdeaProjects                                                                                                         ~
scanning /Users/calebcushing/IdeaProjects ... [done]
> scd aurelia                                                                                                                    ~
a) ~/IdeaProjects/warmeister2.bak/node_modules/aurelia   b) ~/IdeaProjects/warmeister2.bak/node_modules/@aurelia
> cat .scdignore                                                                                                                 ~
*/node_modules/*
> ls IdeaProjects/aurelia                                                                                                        ~
CONTRIBUTING.md        coverage               node_modules           renovate.json
LICENSE                docs                   package-lock.json      scripts
README.md              examples               package.json           test
aurelia.code-workspace lerna.json             packages               tsconfig.json
```

**Comment by xenoterracide** [comment]
reason I missed this option btw, is ohmyzsh has an incomplete copy of the readme, maybe it should just point to the readme here https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/scd

**Comment by pavoljuhas** [comment]
I see - the `scd` version in ohmyzsh is old and does not have scdignore.
I will make a PR to OMZ soon.
For now, you can replace their `scd` script with its version from here.

**Comment by pavoljuhas** [comment]
scd upgraded on OMZ - https://github.com/ohmyzsh/ohmyzsh/pull/9066.
